### ISSUE TITLE
Add parent approval process for task done

### ISSUE THREAD

**Issue by liuhao** [lvshuncn/child_reward_store#1]
While children can claim they completed a task, parent approval is required before the system can give task reward points.

**Comment by lvshuncn** [comment]
Hello, thank you very much for your feedback.

If a child completes a task created by the parent on their own device, the parent needs to approve it before points are awarded.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/3152a389-efaa-4413-af09-a6f157f58abf">
<img width="440" alt="image" src="https://github.com/user-attachments/assets/661fd653-0277-4fcf-92dc-64a59a597320">

**Comment by lvshuncn** [comment]
This feature already exists. Thank you very much for your feedback.
